# Generated by Django 3.1.7 on 2021-06-01 13:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210531_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(default='f1ab56dda384742364d8c46ff90e642b4c281f563dc44082e925569c85282c2a', max_length=64)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2021, 6, 1, 13, 40, 58, 176470, tzinfo=utc))),
                ('activated_at', models.DateTimeField(default=None, null=True)),
                # ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
