# Generated by Django 3.1.7 on 2021-06-13 08:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210601_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 13, 8, 45, 47, 417341, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='activation',
            name='token',
            field=models.CharField(default='7fc9cf1aed79e46e02064de7184f3b6b4488a07a7eec27ecbbd40bd4637d4347', max_length=64),
        ),
    ]
