# Generated by Django 3.1.7 on 2021-06-13 20:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210613_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 13, 21, 26, 42, 339018, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='activation',
            name='token',
            field=models.CharField(default='ef29d0798c31841cafa0138560a271658abdf5f15fa54a464c030bb9bbb95cc7', max_length=64),
        ),
    ]
