# Generated by Django 3.1.7 on 2021-06-15 08:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210614_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 15, 8, 32, 49, 305989, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='activation',
            name='token',
            field=models.CharField(default='7b6ab36ad81b3ef7bff8595b2f08747cdbdece93d3f85c279ca9788cbbf7153e', max_length=64),
        ),
    ]
