# Generated by Django 3.1.7 on 2021-06-17 11:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210615_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 17, 11, 30, 25, 18527, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='activation',
            name='token',
            field=models.CharField(default='9c910cbd892da9b70699f4041a498c19177ad937d82519ba1d5133b32eb900e3', max_length=64),
        ),
    ]
