# Generated by Django 3.1.7 on 2021-06-17 11:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210617_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 17, 11, 33, 44, 784344, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='activation',
            name='token',
            field=models.CharField(default='86c0c4d3cc284edf47dcd0991dce62a622f05bdc082f6b6eacbb21081e378b52', max_length=64),
        ),
    ]
