# Generated by Django 3.1.7 on 2021-06-17 11:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210617_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 17, 11, 37, 24, 664016, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='activation',
            name='token',
            field=models.CharField(default='55230e8be8aae7f848147fb6de2fb508b6661c6ef80dc7977c9b08838ffa3917', max_length=64),
        ),
    ]
