# Generated by Django 3.1.7 on 2021-06-17 21:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20210617_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 17, 22, 6, 11, 588730, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='activation',
            name='token',
            field=models.CharField(default='0ed099913c54df2235aa13f4ad834afb89078b72afe81bade6fae1fd06337ad9', max_length=64),
        ),
    ]
