SHIPPING_ADDRESS = 1
BILLING_ADDRESS = 2
ACTIVATION_AVAILABILITY = {
    'unit': 'minutes',
    'value': 30,
}
ACTIVATION_AVAILABILITY_DICT = {
    ACTIVATION_AVAILABILITY['unit']: ACTIVATION_AVAILABILITY['value']
}

ACTIVE_STATUS = 1
REQUESTED_STATUS = 2
INACTIVE_STATUS = 3

