# Generated by Django 3.1.7 on 2021-06-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210617_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Open'), ('2', 'Approved'), ('3', 'Rejected'), ('4', 'Shipment'), ('5', 'Closed'), ('6', 'Cancelled')], default='1', max_length=2),
        ),
    ]
