# Generated by Django 3.1.7 on 2021-05-24 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210524_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='donor',
            new_name='user_id',
        ),
    ]
