# Generated by Django 3.1.7 on 2021-05-28 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210528_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='user_id',
            new_name='user',
        ),
    ]
