# Generated by Django 3.1.7 on 2021-06-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='status',
            field=models.IntegerField(choices=[(1, 'Active'), (3, 'Inactive'), (2, 'Requested')], default=1),
        ),
    ]
