# Generated by Django 3.1.7 on 2021-06-17 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_products_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
